// Generated by gencpp from file baxter_core_msgs/BridgePublishersForceResponse.msg
// DO NOT EDIT!


#ifndef BAXTER_CORE_MSGS_MESSAGE_BRIDGEPUBLISHERSFORCERESPONSE_H
#define BAXTER_CORE_MSGS_MESSAGE_BRIDGEPUBLISHERSFORCERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_core_msgs
{
template <class ContainerAllocator>
struct BridgePublishersForceResponse_
{
  typedef BridgePublishersForceResponse_<ContainerAllocator> Type;

  BridgePublishersForceResponse_()
    {
    }
  BridgePublishersForceResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BridgePublishersForceResponse_

typedef ::baxter_core_msgs::BridgePublishersForceResponse_<std::allocator<void> > BridgePublishersForceResponse;

typedef boost::shared_ptr< ::baxter_core_msgs::BridgePublishersForceResponse > BridgePublishersForceResponsePtr;
typedef boost::shared_ptr< ::baxter_core_msgs::BridgePublishersForceResponse const> BridgePublishersForceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace baxter_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_core_msgs/BridgePublishersForceResponse";
  }

  static const char* value(const ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BridgePublishersForceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::baxter_core_msgs::BridgePublishersForceResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_CORE_MSGS_MESSAGE_BRIDGEPUBLISHERSFORCERESPONSE_H
