// Generated by gencpp from file baxter_core_msgs/BridgePublishersForce.msg
// DO NOT EDIT!


#ifndef BAXTER_CORE_MSGS_MESSAGE_BRIDGEPUBLISHERSFORCE_H
#define BAXTER_CORE_MSGS_MESSAGE_BRIDGEPUBLISHERSFORCE_H

#include <ros/service_traits.h>


#include <baxter_core_msgs/BridgePublishersForceRequest.h>
#include <baxter_core_msgs/BridgePublishersForceResponse.h>


namespace baxter_core_msgs
{

struct BridgePublishersForce
{

typedef BridgePublishersForceRequest Request;
typedef BridgePublishersForceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BridgePublishersForce
} // namespace baxter_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::baxter_core_msgs::BridgePublishersForce > {
  static const char* value()
  {
    return "1bbf964be273399ce9036f3aa9de11a5";
  }

  static const char* value(const ::baxter_core_msgs::BridgePublishersForce&) { return value(); }
};

template<>
struct DataType< ::baxter_core_msgs::BridgePublishersForce > {
  static const char* value()
  {
    return "baxter_core_msgs/BridgePublishersForce";
  }

  static const char* value(const ::baxter_core_msgs::BridgePublishersForce&) { return value(); }
};


// service_traits::MD5Sum< ::baxter_core_msgs::BridgePublishersForceRequest> should match
// service_traits::MD5Sum< ::baxter_core_msgs::BridgePublishersForce >
template<>
struct MD5Sum< ::baxter_core_msgs::BridgePublishersForceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_core_msgs::BridgePublishersForce >::value();
  }
  static const char* value(const ::baxter_core_msgs::BridgePublishersForceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_core_msgs::BridgePublishersForceRequest> should match
// service_traits::DataType< ::baxter_core_msgs::BridgePublishersForce >
template<>
struct DataType< ::baxter_core_msgs::BridgePublishersForceRequest>
{
  static const char* value()
  {
    return DataType< ::baxter_core_msgs::BridgePublishersForce >::value();
  }
  static const char* value(const ::baxter_core_msgs::BridgePublishersForceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::baxter_core_msgs::BridgePublishersForceResponse> should match
// service_traits::MD5Sum< ::baxter_core_msgs::BridgePublishersForce >
template<>
struct MD5Sum< ::baxter_core_msgs::BridgePublishersForceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_core_msgs::BridgePublishersForce >::value();
  }
  static const char* value(const ::baxter_core_msgs::BridgePublishersForceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_core_msgs::BridgePublishersForceResponse> should match
// service_traits::DataType< ::baxter_core_msgs::BridgePublishersForce >
template<>
struct DataType< ::baxter_core_msgs::BridgePublishersForceResponse>
{
  static const char* value()
  {
    return DataType< ::baxter_core_msgs::BridgePublishersForce >::value();
  }
  static const char* value(const ::baxter_core_msgs::BridgePublishersForceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BAXTER_CORE_MSGS_MESSAGE_BRIDGEPUBLISHERSFORCE_H
