// Generated by gencpp from file baxter_core_msgs/BridgePublishersAuth.msg
// DO NOT EDIT!


#ifndef BAXTER_CORE_MSGS_MESSAGE_BRIDGEPUBLISHERSAUTH_H
#define BAXTER_CORE_MSGS_MESSAGE_BRIDGEPUBLISHERSAUTH_H

#include <ros/service_traits.h>


#include <baxter_core_msgs/BridgePublishersAuthRequest.h>
#include <baxter_core_msgs/BridgePublishersAuthResponse.h>


namespace baxter_core_msgs
{

struct BridgePublishersAuth
{

typedef BridgePublishersAuthRequest Request;
typedef BridgePublishersAuthResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BridgePublishersAuth
} // namespace baxter_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::baxter_core_msgs::BridgePublishersAuth > {
  static const char* value()
  {
    return "f51cbf89898de17d1a8970c6d8fe552f";
  }

  static const char* value(const ::baxter_core_msgs::BridgePublishersAuth&) { return value(); }
};

template<>
struct DataType< ::baxter_core_msgs::BridgePublishersAuth > {
  static const char* value()
  {
    return "baxter_core_msgs/BridgePublishersAuth";
  }

  static const char* value(const ::baxter_core_msgs::BridgePublishersAuth&) { return value(); }
};


// service_traits::MD5Sum< ::baxter_core_msgs::BridgePublishersAuthRequest> should match
// service_traits::MD5Sum< ::baxter_core_msgs::BridgePublishersAuth >
template<>
struct MD5Sum< ::baxter_core_msgs::BridgePublishersAuthRequest>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_core_msgs::BridgePublishersAuth >::value();
  }
  static const char* value(const ::baxter_core_msgs::BridgePublishersAuthRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_core_msgs::BridgePublishersAuthRequest> should match
// service_traits::DataType< ::baxter_core_msgs::BridgePublishersAuth >
template<>
struct DataType< ::baxter_core_msgs::BridgePublishersAuthRequest>
{
  static const char* value()
  {
    return DataType< ::baxter_core_msgs::BridgePublishersAuth >::value();
  }
  static const char* value(const ::baxter_core_msgs::BridgePublishersAuthRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::baxter_core_msgs::BridgePublishersAuthResponse> should match
// service_traits::MD5Sum< ::baxter_core_msgs::BridgePublishersAuth >
template<>
struct MD5Sum< ::baxter_core_msgs::BridgePublishersAuthResponse>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_core_msgs::BridgePublishersAuth >::value();
  }
  static const char* value(const ::baxter_core_msgs::BridgePublishersAuthResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_core_msgs::BridgePublishersAuthResponse> should match
// service_traits::DataType< ::baxter_core_msgs::BridgePublishersAuth >
template<>
struct DataType< ::baxter_core_msgs::BridgePublishersAuthResponse>
{
  static const char* value()
  {
    return DataType< ::baxter_core_msgs::BridgePublishersAuth >::value();
  }
  static const char* value(const ::baxter_core_msgs::BridgePublishersAuthResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BAXTER_CORE_MSGS_MESSAGE_BRIDGEPUBLISHERSAUTH_H
