// Generated by gencpp from file control_msgs/QueryTrajectoryState.msg
// DO NOT EDIT!


#ifndef CONTROL_MSGS_MESSAGE_QUERYTRAJECTORYSTATE_H
#define CONTROL_MSGS_MESSAGE_QUERYTRAJECTORYSTATE_H

#include <ros/service_traits.h>


#include <control_msgs/QueryTrajectoryStateRequest.h>
#include <control_msgs/QueryTrajectoryStateResponse.h>


namespace control_msgs
{

struct QueryTrajectoryState
{

typedef QueryTrajectoryStateRequest Request;
typedef QueryTrajectoryStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryTrajectoryState
} // namespace control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::control_msgs::QueryTrajectoryState > {
  static const char* value()
  {
    return "ec93cdecbd8062d761aa52b7c90cd44b";
  }

  static const char* value(const ::control_msgs::QueryTrajectoryState&) { return value(); }
};

template<>
struct DataType< ::control_msgs::QueryTrajectoryState > {
  static const char* value()
  {
    return "control_msgs/QueryTrajectoryState";
  }

  static const char* value(const ::control_msgs::QueryTrajectoryState&) { return value(); }
};


// service_traits::MD5Sum< ::control_msgs::QueryTrajectoryStateRequest> should match
// service_traits::MD5Sum< ::control_msgs::QueryTrajectoryState >
template<>
struct MD5Sum< ::control_msgs::QueryTrajectoryStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::control_msgs::QueryTrajectoryState >::value();
  }
  static const char* value(const ::control_msgs::QueryTrajectoryStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::control_msgs::QueryTrajectoryStateRequest> should match
// service_traits::DataType< ::control_msgs::QueryTrajectoryState >
template<>
struct DataType< ::control_msgs::QueryTrajectoryStateRequest>
{
  static const char* value()
  {
    return DataType< ::control_msgs::QueryTrajectoryState >::value();
  }
  static const char* value(const ::control_msgs::QueryTrajectoryStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::control_msgs::QueryTrajectoryStateResponse> should match
// service_traits::MD5Sum< ::control_msgs::QueryTrajectoryState >
template<>
struct MD5Sum< ::control_msgs::QueryTrajectoryStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::control_msgs::QueryTrajectoryState >::value();
  }
  static const char* value(const ::control_msgs::QueryTrajectoryStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::control_msgs::QueryTrajectoryStateResponse> should match
// service_traits::DataType< ::control_msgs::QueryTrajectoryState >
template<>
struct DataType< ::control_msgs::QueryTrajectoryStateResponse>
{
  static const char* value()
  {
    return DataType< ::control_msgs::QueryTrajectoryState >::value();
  }
  static const char* value(const ::control_msgs::QueryTrajectoryStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROL_MSGS_MESSAGE_QUERYTRAJECTORYSTATE_H
